# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Aleksei Ustimenko
title: Lead Machine Learning Scientist (Research & Applied Scientist)
email: me@aleksei.uk
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
website: aleksei.uk/me
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jekyllrb
github_username:  takeover
instagram_username: imwhatusee
linkedin_username: aleksei-u-118848a6
googlescholar_username: OES5pK4AAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_5219.PNG
about_content: | # this will include new lines to allow paragraphs
 I'm mathematician that works on industry problems related to A/B testing, RecSys and AI/ML in general.
 
 List of my contrtibutions:
 
 -- 6 conference publications (ICML, ICLR)
 
 -- 2 journal publications
 
 -- 4 patents
 
 -- 91 citations with h-index 5
 
 -- Contributor to open-source library CatBoost
 
 Topics of research that I do:
 
 -- Learning-to-Rank (author of two state-of-the-art algorithms StochasticRank, YetiLoss)
 
 -- Diffusion processes (including simulating quantum mechanics, general theory of convergence of markov chains to diffusion processes, non-convex optimization using Langevin diffusion)
 
 -- Gradient Boosting (convergence and generalization in RKHS, non-convex optimization)
 
 -- Uncertainty estimation (bayesian, gaussian processes using gradient boosting)
 
 -- Non-convex optimization (for recsys)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: ShareChat
        sub_title: Lead Machine Learning Scientist
        caption: July 2022 - Present
        quote: >
          Leading Indian short video app with hundreds millions MAU.
        description: | # this will include new lines to allow paragraphs
          Leading feed ranking modeling efforts and continuing researching science about theoretical foundations of gradient boosting, diffusion processes, learning-to-rank. Managing team of Machine Learning Enginiers to bring state-of-the-art approaches to our recsys. Leading efforts on bringing modern A/B testing techniques.
      - layout: right
        title: Yandex.Research
        sub_title: Research Scientist
        caption: September 2019 - May 2022
        quote: >
          Yandex -- Leading Russian Internal Company (Search Engine, Taxi, Marketplace, etc). Yandex.Research -- lab focused on research.
        description: | # this will include new lines to allow paragraphs
          Researching science about theoretical foundations of gradient boosting, diffusion processes, learning-to-rank. Consulting enginiering teams about how to apply my algorithms. Published 3 papers during my work there and 2 wrote 2 more papers that I've published later.
      - layout: right
        title: Yandex.Market
        sub_title: Data Scientist
        caption: April 2017 - August 2019
        quote: >
          Largest Russian Marketplace (part of Yandex)
        description: | # this will include new lines to allow paragraphs
          Researching science about theoretical foundations of gradient boosting, diffusion processes, learning-to-rank. Consulting enginiering teams about how to apply my algorithms. Invented algorithm StochasticRank that I've published later during work at Research.
      - layout: right
        title: Yandex.Research
        sub_title: Intern Research Scientist
        caption: May 2016 - February 2017
        quote: >
          Leading Russian Internal Company (Search Engine, Taxi, Marketplace, etc).
        description: | # this will include new lines to allow paragraphs
          Researching science about A/B testing and learning-to-select problem for Yandex.Market. As result of my work I've published my first ICML paper.
  
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Lomonosov Moscow State University
        sub_title: BA of Applied Mathematics and Computer Science.
        caption: 2013-2017
        quote: >
          Departamant of numerical methods of linear algebra.
        description: | # this will include new lines to allow paragraphs
          Specialized on tensor decompositions, numerical linear algebra and algebraic geometry. Wrote my first 2 journal publications on linear algebra during my second year.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I'm mathematician with passion about Machine Learning and AI. Even though by background is theoretical and my papers are mostly theoretical I work closely with industry to close the gap between theory and practice by identifying problems of practitioners and implementing theoretically sound solutions to them.
      
      I published 6 conference papers on tier-1 conferences (ICML, ICLR), 2 journal publications on linear algebra and hold 4 patents on my inventions.
      
      I'm passionate about pushing forward theoretical understanding of AI using the most advanced methods of Stochastic Analysis.
      
      All my theoretical breakthroughs have direct applications to industry, e.g. my state-of-the-art learning-to-rank algorithms, uncertainty estimation algorithms, gradient boosting.
      
      I'm contributor to open source library CatBoost.
      
      I'm proficient with C++, Python (including PyTorch and Tensorflow).
      
      I help companies to find flaws in use of ML&Statistics, correctly formalize problems that they try to solve and propose best possible solutions, this includes A/B testing, RecSys, Ranking, Reinforcement Learning.
      
      I have experience of technical leadership and management of teams of Machine Learning Enginiers of size up to 10.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
